apiVersion: v1
kind: Pod
metadata:
  name: custom-scheduler-pod
  namespace: kube-system
spec:
  containers:
    - command:
        - kube-scheduler
        - --address=123.0.0.1
        - --kubeconfig=/etc/kubernetes/scheduler.conf
        - --config=/etc/kubernetes/custom-scheduler-config.yml

        image: k8s.gcr.io/kube-scheduler-amd64:v1.11.2
        name: kube-scheduler