apiVersion: kube-scheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: custom-scheduler
leaderElection:
  leaderElect: true
  resourceNamespace: kube-system   
  resourceName: lock-object-custom-scheduler 