services:
  drupal:
    image: bretfisher/custom-drupal
    build: .
    ports:
      - "8080:80"

  postgres:
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql-pw 
    secrets:
      - psql-pw
    volumes:
      - ./sample-data:/var/lib/postgresql/data

secrets:
  psql-pw:
    file: .sample-3/secrets/psql-pw.txt