apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2026-02-04T01:09:29Z"
  generation: 1
  labels:
    app: kube-prometheus-stack-prometheus
  name: prometheus-kube-prometheus-prometheus
spec:
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: prometheus-kube-prometheus-alertmanager
      namespace: default
      pathPrefix: /
      port: http-web