apiVersion: v1
kind: Service
metadata:
  name: service-nodeport
  labels:
    app: java-app
spec:
  type: NodePort
  selector:
    app: java-app
  ports:
  - name: http
    # Port exposed internally in the cluster
    port: 8080
    # Port our container is listening on
    targetPort: 8080    
    # Port exposed externally
    nodePort: 30007     
    protocol: TCP
    # Preserves client source IP
  externalTrafficPolicy: Local  