apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
  labels:
    app: myapp

spec:
  selector:
    matchLabels:
      app: myapp
      env: production
  replicas: 3
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp
        env: production
    spec:  
      containers:
        - name: nginx
          image: nginx
          