apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
      - kube-apiserver
      - --authorization-mode=Node, RBAC
      - --advertise-address=127.0.0.1
      - --allow-privileged=true
      - --enable-admission-plugins=NodeRestriction
      - --enable-bootstrap-token-auth-true

      image: k8s.gcr.io/kube-apiserver-amd64:v1.11.3
      name: kube-apiserver