kind: KubletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  x509:
    clientCAFile: "/var/lib/kubernetes/ca.pem"
authorization:
  mode: Webhook 
cluserDomain: "cluster.local"
clusterDNS:
  - "10.96.0.1"
podCIDR: "${POD_CIDR}"
resolvConf: "/run/systemd/resolve/resolv.conf"
runtimeRequestTimeout: "15m"
tlsCertFile: "/var/lib/kublet/kubelet-node01.crt" 
tlsPrivateKeyFile: "/var/lib/kublet/kubelet-node01.key"