apiVersion: v1
kind: Pod
metadata:
  name: num-gen
spec:
  containers:
  - name: random-number-generator
    image: alpine:latest
    command: ["/bin/sh", "-c"]
    args: ["shuf -i 0-100 -n 1 >> /opt/number.out; echo 'Number generated'"]
    volumeMounts:
      - mountPath: /opt
        name: data-volume
    ports:
      - containerPort: 8080
  volumes:
    - name: data-volume
      hostPath:
        path: /data
        type: DirectoryOrCreate