apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: google-storage

provisioner: kubernetes.io/gce-pd
parameters:
  # [pd-standard | pd-ssd]
  type: pd-standard
  # [none | regional-pd]
  repliation-type: none