apiVersion: v1
kind: apiVersion: v1
kind: Pod
metadata:
  name: simple-web-app-color
  labels:
    app.kubernetes.io/name: simple-web-app-color
spec:
  containers:
  - name: simple-web-app-color
    image: simple-web-app-color
    ports: 
    - containerPort: 8080
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
