apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000

  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ["/bin/sleep", "infinity"]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          runAsUser: 1000
        readOnlyRootFilesystem: true
      