apiVersion: v1
kind: Pod
metadata:
  name: my-apache
  labels:
    name: my-httpd

spec:
  containers:
    - name: apache-container
      image: httpd:alpine
        ports:
          - containerPort: 80
            name: httpd