apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dep
  labels:
    tier: frontend
    app: my-dep
spec:
  selector:
    matchLabels:
      app: my-apache
  replicas: 5
  template:
    metadata:
      name: nginx
      labels:
        app: my-apache
    spec:
      containers:
      - name: my-apache
        image: httpd:alpine
        ports:
          - containerPort: 80
        