apiversion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: developer-namespace
  name: developer 
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["ConfigMap"]
    verbs: ["create", "update", "delete"]