apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  awsElasticBlockStore:
    volumeID: "my-volume-12345678"
    fsType: "ext4"